/* CREAR BASE DE DATOS*/ 
CREATE DATABASE ADMIN_GASTOS_DB;
GO

/* USAR LA BASE */
USE ADMIN_GASTOS_DB;
GO

/* 1. CREAR TABLA USUARIO */
CREATE TABLE USUARIO
(
    IdUsuario INT IDENTITY(1,1) PRIMARY KEY,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NULL,
    FechaNac DATE NULL,
    ImagenURL VARCHAR(255) NULL,
    Estado BIT NOT NULL
);

/* 2. CREAR TABLA HOGAR */
CREATE TABLE HOGAR
(
    IdHogar INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    IdUsuario INT NOT NULL,
    Estado BIT NOT NULL,
    FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario)
);

/* 3. CREAR TABLA HOGAR_USUARIO */
CREATE TABLE HOGAR_USUARIO
(
    IdMiembro INT IDENTITY(1,1) PRIMARY KEY,
    IdHogar INT NOT NULL,
    IdUsuario INT NOT NULL,
    Rol VARCHAR(20) NOT NULL,
    Estado BIT NOT NULL,
    FOREIGN KEY (IdHogar) REFERENCES HOGAR(IdHogar),
    FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario)
);

/* 4. CREAR TABLA CATEGORIA */
CREATE TABLE CATEGORIA
(
    IdCategoria INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Tipo INT NOT NULL,
    IdUsuario INT NOT NULL,
    IdHogar INT NULL,
    Estado BIT NOT NULL,
    FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario),
    FOREIGN KEY (IdHogar) REFERENCES HOGAR(IdHogar)
);

/* 5. CREAR TABLA MEDIOPAGO */
CREATE TABLE MEDIOPAGO
(
    IdMedioPago INT IDENTITY(1,1) PRIMARY KEY,
    Tipo INT NOT NULL,
    Descripcion VARCHAR(100) NOT NULL,
    DiaCierre INT NULL,
    DiaVencimiento INT NULL,
    IdUsuario INT NOT NULL,
    IdHogar INT NULL,
    Estado BIT NOT NULL,
    FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario),
    FOREIGN KEY (IdHogar) REFERENCES HOGAR(IdHogar)
);

/* 6. CREAR TABLA INGRESO */
CREATE TABLE INGRESO
(
    IdIngreso INT IDENTITY(1,1) PRIMARY KEY,
    Descripcion VARCHAR(150) NOT NULL,
    Fecha DATE NOT NULL,
    Monto DECIMAL(18,2) NOT NULL,
    IdCategoria INT NOT NULL,
    IdUsuario INT NOT NULL,
    IdHogar INT NULL,
    Estado BIT NOT NULL,
    FOREIGN KEY (IdCategoria) REFERENCES CATEGORIA(IdCategoria),
    FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario),
    FOREIGN KEY (IdHogar) REFERENCES HOGAR(IdHogar)
);

/* 7. CREAR TABLA GASTO */
CREATE TABLE GASTO
(
    IdGasto INT IDENTITY(1,1) PRIMARY KEY,
    Fecha DATE NOT NULL,
    MontoPesos DECIMAL(18,2) NOT NULL,
    Moneda INT NOT NULL,
    MontoUSD DECIMAL(18,2) NULL,
    Cotizacion DECIMAL(18,2) NULL,
    Descripcion VARCHAR(200) NOT NULL,
    IdCategoria INT NOT NULL,
    IdMedioPago INT NOT NULL,
    IdUsuario INT NOT NULL,
    IdHogar INT NULL,
    Estado BIT NOT NULL,
    FOREIGN KEY (IdCategoria) REFERENCES CATEGORIA(IdCategoria),
    FOREIGN KEY (IdMedioPago) REFERENCES MEDIOPAGO(IdMedioPago),
    FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario),
    FOREIGN KEY (IdHogar) REFERENCES HOGAR(IdHogar)
);

/* 8. CREAR TABLA CUOTA */
CREATE TABLE CUOTA
(
    IdCuota INT IDENTITY(1,1) PRIMARY KEY,
    IdGasto INT NOT NULL,
    NumeroCuota INT NOT NULL,
    Monto DECIMAL(18,2) NOT NULL,
    Vencimiento DATE NOT NULL,
    Estado VARCHAR(20) NOT NULL,
    FOREIGN KEY (IdGasto) REFERENCES GASTO(IdGasto)
);

/* 9. CREAR TABLA META_AHORRO */
CREATE TABLE META_AHORRO
(
    IdMeta INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    MontoObjetivo DECIMAL(18,2) NOT NULL,
    FechaObjetivo DATE NULL,
    IdUsuario INT NOT NULL,
    IdHogar INT NULL,
    Estado VARCHAR(20) NOT NULL,
    FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario),
    FOREIGN KEY (IdHogar) REFERENCES HOGAR(IdHogar)
);

/* 10. CREAR TABLA DEUDA */
CREATE TABLE DEUDA
(
    IdDeuda INT IDENTITY(1,1) PRIMARY KEY,
    IdUsuario INT NOT NULL,
    NombreDeudor VARCHAR(100) NOT NULL,
    EmailDeudor VARCHAR(100) NOT NULL,
    Descripcion VARCHAR(200) NULL,
    MontoTotal DECIMAL(18,2) NOT NULL,
    Cuotas INT NULL,
    FechaInicio DATE NOT NULL,
    Estado VARCHAR(20) NOT NULL,
    FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario)
);
GO